最新のデータを取得
kikudesuyo/price-comparison pull request #11
Opened 2022-12-09 13:34 UTC by kikudesuyo

fixed #9

2022-12-10 12:37 UTC, kikudesuyo reviewed
https://github.com/kikudesuyo/price-comparison/pull/11/commits/36ee11a9572c9cfd0a74940647a994ccf40e3831
グラフの表示方法を変更
```util.py```の```read_csv```の中にある```prices```が```[12\n, 14\n]```のように改行コードが含まれているが、問題なくint型として動いたけどこれは修正するべき？
修正の方法をかなり考えたけど分からなかったので教えてほしいです。

2022-12-20 04:17 UTC, eteRnaL198 commented
> util.pyのread_csvの中にあるpricesが[12\n, 14\n]のように改行コードが含まれているが、

[rstrip()](https://www.sejuku.net/blog/50412)を使って文末の改行コードを消せるよ

2023-03-01 07:42 UTC, kikudesuyo commented
> 

[15ff9ad](https://github.com/kikudesuyo/price-comparison/pull/11/commits/15ff9ad5d9e5decdf64d1d5474e1fe0082a67901)
ありがとうー改行コード消せました

2023-03-01 10:46 UTC, eteRnaL198 commented
このプルリクはあと何の実装が残ってる？

2023-03-08 06:07 UTC, kikudesuyo commented
> このプルリクはあと何の実装が残ってる？

特には残ってないかな

2023-03-19 12:18 UTC, eteRnaL198 requested changes

2023-03-19 12:18 UTC, eteRnaL198 commented on src/draw_graph.py
> +today = dubble_list[0]
他のファイルからimportできるように､`draw_graph()`関数にした方が良いね

2023-03-19 12:42 UTC, eteRnaL198 requested changes

2023-03-19 12:42 UTC, eteRnaL198 commented on src/util.py
> +        price(str):
返り値はただの文字列ではなく､文字列が入ったリストだから↓が適切
```
dates(list[str]):
price(list[str]):
```

2023-03-19 12:42 UTC, eteRnaL198 commented on src/util.py
> +        price = price.rstrip("\n")
`rstrip`を途中に挟めそう
```python
[date, price] = line.rstrip('\n').split(',')
```

2023-03-19 12:42 UTC, eteRnaL198 commented on src/draw_graph.py
> +dubble_list = read_csv("/data/mouse.csv")
[分割代入](https://tech.515hikaru.net/post/2020-01-13/)でスッキリさせよう
```python
dates, prices = read_csv()
```

2023-03-19 12:42 UTC, eteRnaL198 commented on src/util.py
> +    """日付と価格を出力
`read_csv`だとcsvを読み込んで何するのかわからないから､ファイルのデータを取得するという意味を込めて`get_data()`or`extract_data()`or`get_history()`とかがいいかなぁ｡もっと良いの思いついたら命名決めていいよ

あと､コメントも"出力"というより"取得"or"抽出"かな

2023-03-21 08:18 UTC, kikudesuyo commented on src/util.py
> +        price(str):
確かに間違えてるわ

2023-03-21 08:24 UTC, kikudesuyo commented on src/draw_graph.py
> +today = dubble_list[0]
了解です！
`draw_graph(csv_file)`っていうふうな感じにしたけど引数は適切かな？
https://github.com/kikudesuyo/price-comparison/pull/11/commits/bf267e95df7922c6ed9a94b144b01357bc75b9eb

2023-03-21 08:29 UTC, kikudesuyo commented on src/util.py
> +        price = price.rstrip("\n")
ホントだ、なるべく行数は少なくするっていう意識でいい？

2023-03-21 08:56 UTC, kikudesuyo commented on src/draw_graph.py
> +dubble_list = read_csv("/data/mouse.csv")
こんな感じで出来るのか。javascriptでも出来るんだね。
あと、日付と価格は今までのデータからだから変数名を変更しておきます。
https://github.com/kikudesuyo/price-comparison/pull/11/commits/9727f0db744190c83dcae315849ca6cb835416d3

2023-03-21 09:07 UTC, kikudesuyo commented on src/util.py
> +    """日付と価格を出力
なるほどね、関数の中でやっていることを名前にするっていうより、与えられた変数に対して何を返すのかってことに注目するべきだね。
https://github.com/kikudesuyo/price-comparison/pull/11/commits/263c66fda2ae9e3e14230cba0df68d7afddb74c2

2023-03-21 11:52 UTC, eteRnaL198 commented on src/draw_graph.py
> +today = dubble_list[0]
> 引数は適切かな？

`filename`と迷うけど､`csv_file`で良いと思う-

> 引用ができないんだけど教えてほしい
file changedからコードを選んで､そのコードを引用してコメントを付けれる｡返信とかには引用できないからバッククォーテーションで自力で書くしかない

2023-03-21 11:54 UTC, eteRnaL198 commented on src/util.py
> +        price = price.rstrip("\n")
うん｡基本的にはまとめた方が読みやすくなる
一行が長くなり過ぎちゃう場合は分けたほうが読みやすい

2023-03-21 11:58 UTC, eteRnaL198 commented on src/util.py
> +    """日付と価格を出力
> 関数の中でやっていることを名前にするっていうより、与えられた変数に対して何を返すのかってことに注目するべき

そのとおり！！！！

2023-03-21 12:53 UTC, kikudesuyo commented on src/util.py
> +        price = price.rstrip("\n")
了解です！

2023-03-28 07:53 UTC, kikudesuyo commented
> `.env.json`と`serviceAccountKey.json`がプッシュされちゃってるね .gitignoreに追加してー

追加したのになぜか消えないんだけどなんでかな？

2023-03-28 11:57 UTC, eteRnaL198 commented
@kikudesuyo 
> 追加したのになぜか消えないんだけどなんでかな？

キャッシュ消した？

2023-04-08 13:18 UTC, kikudesuyo reviewed
LGTM!!

2023-04-08 13:18 UTC, eteRnaL198 approved these changes
LGTM

2023-04-08 13:18 UTC, merged